// SrvSocket.idl : IDL source for SrvSocket.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SrvSocket.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(A0C2E940-A4F9-43B1-9336-E9F93E64F275),
	version(1.0),
	helpstring("SrvSocket 1.0 Type Library")
]
library SRVSOCKETLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
